### ISSUE TITLE
音质问题

### ISSUE THREAD

**Issue by 2757227663** [jing332/xmlydownloader#2]
不能下载高清的音质,下载到处音频不清晰

**Comment by jing332** [comment]
你下载的是VIP还是免费音频？

---原始邮件---
发件人: "2757227663"<notifications@github.com&gt;
发送时间: 2020年9月28日(周一) 上午8:22
收件人: "jing332/xmlydownloader"<xmlydownloader@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [jing332/xmlydownloader] 音质问题 (#2)




 
不能下载高清的音质,下载到处音频不清晰

**Comment by 2757227663** [comment]
> 你下载的是VIP还是免费音频？
> […](#)
> ---原始邮件--- 发件人: "2757227663"<notifications@github.com&gt; 发送时间: 2020年9月28日(周一) 上午8:22 收件人: "jing332/xmlydownloader"<xmlydownloader@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [jing332/xmlydownloader] 音质问题 (#2) 不能下载高清的音质,下载到处音频不清晰 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

都试过,vip的也试过,我用猫抓插件不会这样

**Comment by jing332** [comment]
你把音频保存到本地，在属性里看看比特率是24还是64kbps。



---原始邮件---
发件人: "2757227663"<notifications@github.com&gt;
发送时间: 2020年9月28日(周一) 上午9:39
收件人: "jing332/xmlydownloader"<xmlydownloader@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Jing"<3033784236@qq.com&gt;;
主题: Re: [jing332/xmlydownloader] 音质问题 (#2)




  
你下载的是VIP还是免费音频？
 …
 ---原始邮件--- 发件人: "2757227663"<notifications@github.com&gt; 发送时间: 2020年9月28日(周一) 上午8:22 收件人: "jing332/xmlydownloader"<xmlydownloader@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [jing332/xmlydownloader] 音质问题 (#2) 不能下载高清的音质,下载到处音频不清晰 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
都试过,vip的也试过,我用猫抓插件不会这样

**Comment by jing332** [comment]
http://mobwsa.ximalaya.com/mobile/playlist/album/page?albumId=16805359&pageId=1
看来是喜马拉雅改Mobile免费接口比特率了，全是24kbps。PC付费接口还不知道，等有空我看看。

**Comment by 2757227663** [comment]
> 你把音频保存到本地，在属性里看看比特率是24还是64kbps。
> […](#)
> ---原始邮件--- 发件人: "2757227663"<notifications@github.com&gt; 发送时间: 2020年9月28日(周一) 上午9:39 收件人: "jing332/xmlydownloader"<xmlydownloader@noreply.github.com&gt;; 抄送: "Comment"<comment@noreply.github.com&gt;;"Jing"<3033784236@qq.com&gt;; 主题: Re: [jing332/xmlydownloader] 音质问题 (#2) 你下载的是VIP还是免费音频？ … ---原始邮件--- 发件人: "2757227663"<notifications@github.com&gt; 发送时间: 2020年9月28日(周一) 上午8:22 收件人: "jing332/xmlydownloader"<xmlydownloader@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [jing332/xmlydownloader] 音质问题 (#2) 不能下载高清的音质,下载到处音频不清晰 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. 都试过,vip的也试过,我用猫抓插件不会这样 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

64kbps,我发现有时能下载高清的,有时下载不清晰,一个19分钟的音频一般下载的时候有10多mb的大小,用喜马拉雅app下载的时候就有10多mb大小,而用各种第三方下载软件下载时,有时能下载到原音质,有时不能

**Comment by jing332** [comment]
http://aod.cos.tx.xmcdn.com/group50/M01/50/08/wKgKnVvjnbvirPYtAFDbWeKbAzU917.m4a
搞错了…喜马拉雅并没动免费接口 =_=

**Comment by jing332** [comment]
> > 你把音频保存到本地，在属性里看看比特率是24还是64kbps。
> > […](#)
> > ---原始邮件--- 发件人: "2757227663"<[notifications@github.com](mailto:notifications@github.com)> 发送时间: 2020年9月28日(周一) 上午9:39 收件人: "jing332/xmlydownloader"<[xmlydownloader@noreply.github.com](mailto:xmlydownloader@noreply.github.com)>; 抄送: "Comment"<[comment@noreply.github.com](mailto:comment@noreply.github.com)>;"Jing"<[3033784236@qq.com](mailto:3033784236@qq.com)>; 主题: Re: [jing332/xmlydownloader] 音质问题 (#2) 你下载的是VIP还是免费音频？ … ---原始邮件--- 发件人: "2757227663"<[notifications@github.com](mailto:notifications@github.com)> 发送时间: 2020年9月28日(周一) 上午8:22 收件人: "jing332/xmlydownloader"<[xmlydownloader@noreply.github.com](mailto:xmlydownloader@noreply.github.com)>; 抄送: "Subscribed"<[subscribed@noreply.github.com](mailto:subscribed@noreply.github.com)>; 主题: [jing332/xmlydownloader] 音质问题 (#2) 不能下载高清的音质,下载到处音频不清晰 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. 都试过,vip的也试过,我用猫抓插件不会这样 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> 64kbps,我发现有时能下载高清的,有时下载不清晰,一个19分钟的音频一般下载的时候有10多mb的大小,用喜马拉雅app下载的时候就有10多mb大小,而用各种第三方下载软件下载时,有时能下载到原音质,有时不能

没办法复现问题，我也不知道原因。
